export { validateEmail } from './validateEmail'
export { validateName } from './validateName'
export { validatePassword } from './validatePassword'
export { validateOrderItems } from './validateOrderItems'
export { validateSingleString } from './validateSingleString'
export { validateShippingAddress } from './validateShippingAddress'
export { validateNumber } from './validateNumber'
